#!/bin/sh

# Required when using NVM to manage Node versions, for some reason.
if test -f $HOME/.nvm/nvm.sh; then
    . $HOME/.nvm/nvm.sh
fi

# Make sure we're navigated to the top level of the git tree
cd "$(git rev-parse --show-toplevel)"

# Set the location of the ESLint, TypeScript, and Playwright binaries
ESLINT="./node_modules/.bin/eslint"
TSC="./node_modules/.bin/tsc"
CUR_DIR=pwd
pwd

# If ESLint is not installed display an error and exit, preventing commit.
if [[ ! -x "$ESLINT" ]]; then
    printf "ESLint does not seem to be installed\n"
    exit 1
fi

# If TypeScript is not installed display an error and exit, preventing commit.
if [[ ! -x "$TSC" ]]; then
    printf "TypeScript does not seem to be installed\n"
    exit 1
fi

# Perform Linting
npm run lint
EXIT_CODE="$?"

# If ESlint exited without error, commit can go ahead. Otherwise, stop.
if [[ "${EXIT_CODE}" != 0 ]]; then
    printf "\nPRE-COMMIT LINTING FAILED: Please fix errors and try again.\n"
    exit 1
fi

# Perform Type Checks
npm run type-check
EXIT_CODE="$?"

# If ESlint exited without error, commit can go ahead. Otherwise, stop.
if [[ "${EXIT_CODE}" != 0 ]]; then
    printf "\nPRE-COMMIT TYPE CHECKS FAILED: Please fix errors and try again.\n"
    exit 1
fi

exit $?
