#!/bin/sh

# Required when using NVM to manage Node versions, for some reason.
if test -f $HOME/.nvm/nvm.sh; then
    . $HOME/.nvm/nvm.sh
fi

# Make sure we're navigated to the top level of the git tree
cd "$(git rev-parse --show-toplevel)"

# Set the location of the ESLint, TypeScript, and Playwright binaries
PLAYWRIGHT="./node_modules/.bin/playwright"
CUR_DIR=pwd
pwd

# If TypeScript is not installed display an error and exit, preventing commit.
if [[ ! -x "$PLAYWRIGHT" ]]; then
    printf "Playwright does not seem to be installed\n"
    exit 1
fi

# Run Tests
npm run test
EXIT_CODE="$?"

# If ESlint exited without error, commit can go ahead. Otherwise, stop.
if [[ "${EXIT_CODE}" != 0 ]]; then
    printf "\nPRE-COMMIT TESTS FAILED: Please fix errors and try again.\n"
    exit 1
fi

exit $?
